[package]
name = "bevy_gltf_components_basic_example"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.12"
bevy_gltf_components = "0.3.0"
bevy_rapier3d = { version = "0.23.0", features = [
  "serde-serialize",
  "debug-render-3d",
  "enhanced-determinism",
] }
bevy_editor_pls = { version = "0.6" }
